### ISSUE TITLE
I2C Extender Board Testing

### ISSUE THREAD

**Issue by alexeiaburgos** [OPEnSLab-OSU/WeatherChimes#132]
- [ ] Stage #1 of Testing:

> - [ ] Test I2C Extender with ethernet cable that is less than 3 ft.
> - [ ] Use a variable I2C sensor (i.e. Accelerometer) 

- [ ] Stage #2 of Testing:

> - [ ] Test I2C Extender with ethernet cable with a minimum length of 20 ft.
>- [ ] Check the current draw at the end of ethernet cable at this length
> - [ ] Do this same current draw test same test with with ethernet cable with min. length of 30 ft.

- [ ] Stage #3 of Testing (Official Field Testing):

> - [ ] Test I2C Extender with ethernet cable with a minimum length of 30 ft.
>- [ ] Attach Osmopod and/or EZO DO Probe and install at a field site

**Comment by alexeiaburgos** [comment]
Within Stage 1 testing, the receiving end of the board is at 1.8V voltage, seeing a voltage drop from the wire. The ethernet cable has an internal resistance between the VCC & GND of 350 ohm. To mitigate this voltage drop, we can decrease the current flowing through the cable by increasing the resistor values of the receiving and transmitting boards by a factor of 10. This will decrease the flow of current that is approximatively 3 mA to 0.3 mA, thus reducing the voltage drop across ethernet cable

**Comment by alexeiaburgos** [comment]
Stage 1 - Used another ethernet cable, the I2C Extender was able to power the sensor and communicate properly. The internal resistance between VCC & GND was zero measured at 0 ohms across the wire. The internal resistance between wires on the VCC/GND was measured at 7 ohms.

**Comment by alexeiaburgos** [comment]
Stage 2 - Casey tested I2C Extender with SHT: Current draw was 1mAh and 9mWh over 3 minutes

**Comment by alexeiaburgos** [comment]
Stage 3 - Tested with Osmopod w/ cable length of 20ft. Instantaneous Current draw was 32 mA. Osmopods are having issues initializing. Next step would be to do a field installation
